version: "3.8"

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
