---
- name: Install Python Flask on backend server
  hosts: backend
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask using pip
      pip:
        name: Flask
        executable: pip3

- name: Install Docker and MySQL on db server
  hosts: db
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Pull MySQL Docker image
      docker_image:
        name: mysql
        tag: latest

    - name: Run MySQL container
      docker_container:
        name: mysql_container
        image: mysql:latest
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: "PassW@rd!"
          MYSQL_DATABASE: "db"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "PassW@rd!"
        ports:
          - "3306:3306"
